* added --disable-speex and --disable-gsm configure options  * added pre-processor options to disable codec code  * TODO: will crash if codec is unsupported
git-svn-id: http://svn.mangler.org/mangler/trunk@500 f654edcb-a5fb-4f28-a0e7-68c327795dae

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -893,6 +893,8 @@ enable_fast_install
 with_gnu_ld
 enable_libtool_lock
 enable_glibtest
+enable_gsm
+enable_speex
 enable_pulseaudio
 enable_alsa
 '
@@ -1551,6 +1553,8 @@ Optional Features:
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --disable-glibtest      do not try to compile and run a test GLIB program
+  --disable-gsm           disable GSM codec support
+  --disable-speex         disable Speex codec support
   --disable-pulseaudio    disable PulseAudio support
   --enable-alsa           enable ALSA support
 
@@ -5448,13 +5452,13 @@ if test "${lt_cv_nm_interface+set}" = set; then :
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5451: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5455: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5454: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5458: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5457: output\"" >&5)
+  (eval echo "\"\$as_me:5461: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6649,7 +6653,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6652 "configure"' > conftest.$ac_ext
+  echo '#line 6656 "configure"' > conftest.$ac_ext
   if { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_compile\""; } >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8569,11 +8573,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8572: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8576: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8576: \$? = $ac_status" >&5
+   echo "$as_me:8580: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8908,11 +8912,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8911: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8915: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8915: \$? = $ac_status" >&5
+   echo "$as_me:8919: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9013,11 +9017,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9016: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9020: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9020: \$? = $ac_status" >&5
+   echo "$as_me:9024: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9068,11 +9072,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9071: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9075: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9075: \$? = $ac_status" >&5
+   echo "$as_me:9079: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11448,7 +11452,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11451 "configure"
+#line 11455 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11544,7 +11548,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11547 "configure"
+#line 11551 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13500,11 +13504,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13503: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13507: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13507: \$? = $ac_status" >&5
+   echo "$as_me:13511: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13599,11 +13603,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13602: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13606: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13606: \$? = $ac_status" >&5
+   echo "$as_me:13610: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13651,11 +13655,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13654: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13658: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13658: \$? = $ac_status" >&5
+   echo "$as_me:13662: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15433,7 +15437,20 @@ fi
 fi
 
 
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for gsm_create in -lgsm" >&5
+
+# Check whether --enable-gsm was given.
+if test "${enable_gsm+set}" = set; then :
+  enableval=$enable_gsm; disable_gsm=yes
+fi
+
+# Check whether --enable-speex was given.
+if test "${enable_speex+set}" = set; then :
+  enableval=$enable_speex; disable_speex=yes
+fi
+
+
+if test "$enable_gsm" != "no" ; then
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for gsm_create in -lgsm" >&5
 $as_echo_n "checking for gsm_create in -lgsm... " >&6; }
 if test "${ac_cv_lib_gsm_gsm_create+set}" = set; then :
   $as_echo_n "(cached) " >&6
@@ -15478,27 +15495,29 @@ _ACEOF
 
 else
 
-	echo "error: cannot find libgsm: Is it installed? Also make sure you have the"
-	echo "       libgsm development packages installed"
-	exit -1
+		echo "error: cannot find libgsm: Is it installed? Also make sure you have the"
+		echo "       libgsm development packages installed"
+		exit -1
 
 fi
 
-ac_fn_c_check_header_mongrel "$LINENO" "gsm.h" "ac_cv_header_gsm_h" "$ac_includes_default"
+	ac_fn_c_check_header_mongrel "$LINENO" "gsm.h" "ac_cv_header_gsm_h" "$ac_includes_default"
 if test "x$ac_cv_header_gsm_h" = x""yes; then :
 
 $as_echo "#define HAVE_GSM_H 1" >>confdefs.h
 
 else
 
-	ac_fn_c_check_header_mongrel "$LINENO" "gsm/gsm.h" "ac_cv_header_gsm_gsm_h" "$ac_includes_default"
+		ac_fn_c_check_header_mongrel "$LINENO" "gsm/gsm.h" "ac_cv_header_gsm_gsm_h" "$ac_includes_default"
 if test "x$ac_cv_header_gsm_gsm_h" = x""yes; then :
+
+$as_echo "#define HAVE_GSM_GSM_H 1" >>confdefs.h
 
 else
 
-		echo "error: found gsm libraries, but headers are missing or corrupt. are you"
-		echo "       missing a libgsm development package?"
-		exit -1
+			echo "error: found gsm libraries, but headers are missing or corrupt. are you"
+			echo "       missing a libgsm development package?"
+			exit -1
 
 fi
 
@@ -15507,9 +15526,18 @@ fi
 fi
 
 
+
+$as_echo "#define HAVE_GSM 1" >>confdefs.h
+
+else
+
+$as_echo "#define HAVE_GSM 0" >>confdefs.h
+
+fi
 
 
 # Checks for header files.
+if test "$enable_speex" != "no" ; then
 
 pkg_failed=no
 { $as_echo "$as_me:${as_lineno-$LINENO}: checking for speex" >&5
@@ -15602,6 +15630,14 @@ $as_echo "yes" >&6; }
 fi
 
 
+
+$as_echo "#define HAVE_SPEEX 1" >>confdefs.h
+
+else
+
+$as_echo "#define HAVE_SPEEX 0" >>confdefs.h
+
+fi
 
 
 pkg_failed=no
