* implementing super.hater.patch (OSS support)  * modified configure to show audio subsystem warnings instead of errors  * might need a dlopen up in here  * 100% untested
git-svn-id: http://svn.mangler.org/mangler/trunk@760 f654edcb-a5fb-4f28-a0e7-68c327795dae

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -907,6 +907,7 @@ enable_xosd
 enable_g15
 with_pulseaudio
 with_alsa
+with_oss
 '
       ac_precious_vars='build_alias
 host_alias
@@ -1581,6 +1582,7 @@ Optional Packages:
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
   --without-pulseaudio    disable support for PulseAudio
   --without-alsa          disable support for ALSA
+  --without-oss           disable support for OSS
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -5503,13 +5505,13 @@ if test "${lt_cv_nm_interface+set}" = set; then :
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5506: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5508: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5509: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5511: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5512: output\"" >&5)
+  (eval echo "\"\$as_me:5514: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6704,7 +6706,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6707 "configure"' > conftest.$ac_ext
+  echo '#line 6709 "configure"' > conftest.$ac_ext
   if { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_compile\""; } >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8624,11 +8626,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8627: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8629: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8631: \$? = $ac_status" >&5
+   echo "$as_me:8633: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8963,11 +8965,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8966: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8968: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8970: \$? = $ac_status" >&5
+   echo "$as_me:8972: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9068,11 +9070,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9071: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9073: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9075: \$? = $ac_status" >&5
+   echo "$as_me:9077: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9123,11 +9125,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9126: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9128: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9130: \$? = $ac_status" >&5
+   echo "$as_me:9132: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11503,7 +11505,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11506 "configure"
+#line 11508 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11599,7 +11601,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11602 "configure"
+#line 11604 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13555,11 +13557,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13558: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13560: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13562: \$? = $ac_status" >&5
+   echo "$as_me:13564: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13654,11 +13656,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13657: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13659: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13661: \$? = $ac_status" >&5
+   echo "$as_me:13663: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13706,11 +13708,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13709: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13711: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13713: \$? = $ac_status" >&5
+   echo "$as_me:13715: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15228,8 +15230,9 @@ main ()
 {
   int major, minor, micro;
   char *tmp_version;
+  int ignored;
 
-  fclose (fopen ("conf.glibtest", "w"));
+  ignored = system ("touch conf.glibtest");
 
   /* HP/UX 9 (%@#!) writes to sscanf strings */
   tmp_version = g_strdup("$min_glib_version");
@@ -15556,7 +15559,7 @@ _ACEOF
 else
 
 		echo "error: cannot find libgsm: Is it installed? Also make sure you have the"
-		echo "       libgsm development packages installed"
+		echo "       libgsm development packages installed."
 		exit -1
 
 fi
@@ -16221,6 +16224,15 @@ else
 fi
 
 
+
+# Check whether --with-oss was given.
+if test "${with_oss+set}" = set; then :
+  withval=$with_oss; :
+else
+  with_oss=yes
+fi
+
+
 if test "x$with_pulseaudio" != xno; then :
 
 
@@ -16285,21 +16297,13 @@ fi
 	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
 
-			echo "**************************************************************************"
-			echo "*** ERROR: pulse audio development libraries or headers were not found ***"
-			echo "*** on your system.  You can disable PulseAudio support with           ***"
-			echo "*** ./configure --without-pulseaudio                                   ***"
-			echo "**************************************************************************"
-			exit 1
+			echo "warning: PulseAudio development libraries or headers were not found."
+			echo "         PulseAudio support is disabled."
 
 elif test $pkg_failed = untried; then
 
-			echo "**************************************************************************"
-			echo "*** ERROR: pulse audio development libraries or headers were not found ***"
-			echo "*** on your system.  You can disable PulseAudio support with           ***"
-			echo "*** ./configure --without-pulseaudio                                   ***"
-			echo "**************************************************************************"
-			exit 1
+			echo "warning: PulseAudio development libraries or headers were not found."
+			echo "         PulseAudio support is disabled."
 
 else
 	pulse_CFLAGS=$pkg_cv_pulse_CFLAGS
@@ -16307,11 +16311,13 @@ else
         { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 $as_echo "yes" >&6; }
 
+
 $as_echo "#define HAVE_PULSE 1" >>confdefs.h
 
+
+
+
 fi
-
-
 
 else
   :
@@ -16381,21 +16387,13 @@ fi
 	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
 $as_echo "no" >&6; }
 
-			echo "**************************************************************************"
-			echo "*** ERROR: ALSA audio development libraries or headers were not found  ***"
-			echo "*** on your system.  You can disable ALSA support with                 ***"
-			echo "*** ./configure --without-alsa                                         ***"
-			echo "**************************************************************************"
-			exit 1
+			echo "warning: ALSA development libraries or headers were not found."
+			echo "         ALSA support is disabled."
 
 elif test $pkg_failed = untried; then
 
-			echo "**************************************************************************"
-			echo "*** ERROR: ALSA audio development libraries or headers were not found  ***"
-			echo "*** on your system.  You can disable ALSA support with                 ***"
-			echo "*** ./configure --without-alsa                                         ***"
-			echo "**************************************************************************"
-			exit 1
+			echo "warning: ALSA development libraries or headers were not found."
+			echo "         ALSA support is disabled."
 
 else
 	alsa_CFLAGS=$pkg_cv_alsa_CFLAGS
@@ -16403,9 +16401,35 @@ else
         { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 $as_echo "yes" >&6; }
 
+
 $as_echo "#define HAVE_ALSA 1" >>confdefs.h
 
+
+
+
 fi
+
+
+else
+  :
+
+fi
+if test "x$with_oss" != xno; then :
+
+		ac_fn_c_check_header_mongrel "$LINENO" "sys/soundcard.h" "ac_cv_header_sys_soundcard_h" "$ac_includes_default"
+if test "x$ac_cv_header_sys_soundcard_h" = x""yes; then :
+
+
+$as_echo "#define HAVE_OSS 1" >>confdefs.h
+
+
+else
+
+			echo "warning: OSS required headers were not found."
+			echo "         OSS support is disabled."
+
+fi
+
 
 
 
@@ -16946,12 +16970,12 @@ done
 ac_config_files="$ac_config_files src/Makefile Makefile libventrilo3/Makefile"
 
 
-if test "x$with_pulseaudio" = xno -a "x$with_alsa" = "xno" ; then
+if test "x$with_pulseaudio" = "xno" -a "x$with_alsa" = "xno" -a "x$with_oss" = "xno" ; then
 	echo "**************************************************************************"
-	echo "*** WARNING: You have disabled support for both PulseAudio and ALSA.   ***"
+	echo "*** WARNING: You have disabled support for PulseAudio, ALSA and OSS.   ***"
 	echo "***          You can compile and use Mangler without an audio          ***"
-	echo "***          subsystem, but you will not have any sound, which more    ***"
-	echo "***          more or less makes the program useless.                   ***"
+	echo "***          subsystem but you will not have any sound, which more     ***"
+	echo "***          or less makes the program useless.                        ***"
 	echo "**************************************************************************"
 fi
 
