seriously this time
git-svn-id: http://svn.mangler.org/mangler/trunk@479 f654edcb-a5fb-4f28-a0e7-68c327795dae

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -746,6 +746,8 @@ LTLIBOBJS
 LIBOBJS
 gthread_LIBS
 gthread_CFLAGS
+alsa_LIBS
+alsa_CFLAGS
 pulse_LIBS
 pulse_CFLAGS
 gtkmm_LIBS
@@ -891,7 +893,8 @@ enable_fast_install
 with_gnu_ld
 enable_libtool_lock
 enable_glibtest
-with_pulseaudio
+enable_pulseaudio
+enable_alsa
 '
       ac_precious_vars='build_alias
 host_alias
@@ -915,6 +918,8 @@ gtkmm_CFLAGS
 gtkmm_LIBS
 pulse_CFLAGS
 pulse_LIBS
+alsa_CFLAGS
+alsa_LIBS
 gthread_CFLAGS
 gthread_LIBS'
 
@@ -1546,6 +1551,8 @@ Optional Features:
                           optimize for fast installation [default=yes]
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --disable-glibtest      do not try to compile and run a test GLIB program
+  --disable-pulseaudio    disable PulseAudio support
+  --enable-alsa           enable ALSA support
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -1553,7 +1560,6 @@ Optional Packages:
   --with-pic              try to use only PIC/non-PIC objects [default=use
                           both]
   --with-gnu-ld           assume the C compiler uses GNU ld [default=no]
-  --without-pulseaudio    disable support for pulseaudio
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -1579,6 +1585,8 @@ Some influential environment variables:
   pulse_CFLAGS
               C compiler flags for pulse, overriding pkg-config
   pulse_LIBS  linker flags for pulse, overriding pkg-config
+  alsa_CFLAGS C compiler flags for alsa, overriding pkg-config
+  alsa_LIBS   linker flags for alsa, overriding pkg-config
   gthread_CFLAGS
               C compiler flags for gthread, overriding pkg-config
   gthread_LIBS
@@ -5440,13 +5448,13 @@ if test "${lt_cv_nm_interface+set}" = set; then :
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5443: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5451: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5446: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5454: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5449: output\"" >&5)
+  (eval echo "\"\$as_me:5457: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -6641,7 +6649,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 6644 "configure"' > conftest.$ac_ext
+  echo '#line 6652 "configure"' > conftest.$ac_ext
   if { { eval echo "\"\$as_me\":${as_lineno-$LINENO}: \"$ac_compile\""; } >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8561,11 +8569,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8564: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8572: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8568: \$? = $ac_status" >&5
+   echo "$as_me:8576: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -8900,11 +8908,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:8903: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:8911: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:8907: \$? = $ac_status" >&5
+   echo "$as_me:8915: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9005,11 +9013,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9008: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9016: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9012: \$? = $ac_status" >&5
+   echo "$as_me:9020: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9060,11 +9068,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9063: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9071: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9067: \$? = $ac_status" >&5
+   echo "$as_me:9075: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11440,7 +11448,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11443 "configure"
+#line 11451 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11536,7 +11544,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 11539 "configure"
+#line 11547 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13492,11 +13500,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13495: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13503: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13499: \$? = $ac_status" >&5
+   echo "$as_me:13507: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13591,11 +13599,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13594: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13602: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13598: \$? = $ac_status" >&5
+   echo "$as_me:13606: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -13643,11 +13651,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13646: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13654: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13650: \$? = $ac_status" >&5
+   echo "$as_me:13658: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15779,16 +15787,51 @@ fi
 
 
 
+# Check whether --enable-pulseaudio was given.
+if test "${enable_pulseaudio+set}" = set; then :
+  enableval=$enable_pulseaudio; disable_pulse=yes
+fi
 
-# Check whether --with-pulseaudio was given.
-if test "${with_pulseaudio+set}" = set; then :
-  withval=$with_pulseaudio;
-else
-  with_pulseaudio=yes
+# Check whether --enable-alsa was given.
+if test "${enable_alsa+set}" = set; then :
+  enableval=$enable_alsa; enable_alsa=yes
 fi
 
 
-if test "x$with_pulseaudio" != xno; then :
+if test -z "$enable_pulseaudio" -a -z "$enable_alsa" ; then
+	pulseaudio=yes
+	alsa=no
+elif  test "$enable_pulseaudio" = "yes" -a "$enable_alsa" = "yes" ; then
+	echo "error: you cannot enable support for both ALSA and PulseAudio"
+	exit
+elif  test "$enable_pulseaudio" = "no" -a "$enable_alsa" = "no" ; then
+	echo "**************************************************************************"
+	echo "*** WARNING: You have disabled support for both PulseAudio and ALSA.   ***"
+	echo "***          You can compile and use Mangler without an audio          ***"
+	echo "***          subsystem, but you will not have any sound, which more    ***"
+	echo "***          more or less makes the program useless.                   ***"
+	echo "**************************************************************************"
+	pulseaudio=no
+	alsa=no
+elif  test "$enable_pulseaudio" = "no" -a "$enable_alsa" != "yes" ; then
+	echo "**************************************************************************"
+	echo "*** WARNING: You have disabled support for both PulseAudio, but you    ***"
+	echo "***          did not enable ALSA support.  Enabling ALSA by default.   ***"
+	echo "**************************************************************************"
+	pulseaudio=no
+	alsa=yes
+	exit
+elif  test "$enable_pulseaudio" = "yes" ; then
+	echo "Enabling PulseAudio support and disabling ALSA support"
+	pulseaudio=yes
+	alsa=no
+elif  test "$enable_alsa" = "yes" ; then
+	echo "Enabling ALSA support and disabling PulseAudio support"
+	pulseaudio=no
+	alsa=yes
+fi
+
+if test "$pulseaudio" = "yes"; then :
 
 
 pkg_failed=no
@@ -15856,7 +15899,6 @@ $as_echo "no" >&6; }
 			echo "*** ERROR: pulse audio development libraries or headers were not found ***"
 			echo "*** on your system.  You can disable PulseAudio support with           ***"
 			echo "*** ./configure --without-pulseaudio                                   ***"
-			echo "*** but this will disable sound support                                ***"
 			echo "**************************************************************************"
 			exit 1
 
@@ -15866,7 +15908,6 @@ elif test $pkg_failed = untried; then
 			echo "*** ERROR: pulse audio development libraries or headers were not found ***"
 			echo "*** on your system.  You can disable PulseAudio support with           ***"
 			echo "*** ./configure --without-pulseaudio                                   ***"
-			echo "*** but this will disable sound support                                ***"
 			echo "**************************************************************************"
 			exit 1
 
@@ -15882,12 +15923,97 @@ fi
 
 
 
-else
+fi
+if test "$alsa" = "yes"; then :
 
-		echo "**************************************************************************"
-		echo "*** WARNING: compiling without pulse.  you will not have sound support ***"
-		echo "*** PulseAudio 0.9.14 or higher is required for audio support          ***"
-		echo "**************************************************************************"
+
+pkg_failed=no
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for alsa" >&5
+$as_echo_n "checking for alsa... " >&6; }
+
+if test -n "$PKG_CONFIG"; then
+    if test -n "$alsa_CFLAGS"; then
+        pkg_cv_alsa_CFLAGS="$alsa_CFLAGS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"alsa >= 1.0.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "alsa >= 1.0.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_alsa_CFLAGS=`$PKG_CONFIG --cflags "alsa >= 1.0.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+if test -n "$PKG_CONFIG"; then
+    if test -n "$alsa_LIBS"; then
+        pkg_cv_alsa_LIBS="$alsa_LIBS"
+    else
+        if test -n "$PKG_CONFIG" && \
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"alsa >= 1.0.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "alsa >= 1.0.0") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  pkg_cv_alsa_LIBS=`$PKG_CONFIG --libs "alsa >= 1.0.0" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+    fi
+else
+	pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        alsa_PKG_ERRORS=`$PKG_CONFIG --short-errors --errors-to-stdout --print-errors "alsa >= 1.0.0"`
+        else
+	        alsa_PKG_ERRORS=`$PKG_CONFIG --errors-to-stdout --print-errors "alsa >= 1.0.0"`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$alsa_PKG_ERRORS" >&5
+
+	{ $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
+$as_echo "no" >&6; }
+
+			echo "**************************************************************************"
+			echo "*** ERROR: ALSA audio development libraries or headers were not found  ***"
+			echo "*** on your system.  You can disable ALSA support with                 ***"
+			echo "*** ./configure --without-alsa                                         ***"
+			echo "**************************************************************************"
+			exit 1
+
+elif test $pkg_failed = untried; then
+
+			echo "**************************************************************************"
+			echo "*** ERROR: ALSA audio development libraries or headers were not found  ***"
+			echo "*** on your system.  You can disable ALSA support with                 ***"
+			echo "*** ./configure --without-alsa                                         ***"
+			echo "**************************************************************************"
+			exit 1
+
+else
+	alsa_CFLAGS=$pkg_cv_alsa_CFLAGS
+	alsa_LIBS=$pkg_cv_alsa_LIBS
+        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+$as_echo "yes" >&6; }
+
+$as_echo "#define HAVE_ALSA 1" >>confdefs.h
+
+fi
+
 
 
 fi
